#! /usr/bin/env python3

import fileinput
import re
import sys

for line in fileinput.input(files=sys.argv[2:]):
    m = re.match(r'__{0}__\s*=\s*"([^"]*)\"'.format(sys.argv[1]), line)
    if m:
        print(m.group(1))
        exit(0)

exit(1)
